In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(type(arr))

arr2 = np.array((1, 2, 3, 4, 5))
print(type(arr2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr4 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(arr3)
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [5]:
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

1
1
2
3


In [6]:
arr5 = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr5)

[[[[[1 2 3 4 5]]]]]


In [7]:
print('Last element of the array is:', arr3[1, -1])

Last element of the array is: 10


In [8]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr5[-3: -1])
print(arr5[2:8:2])

[8 9]
[3 5 7]


In [9]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


### Data Types in Python
- integer
- float
- string
- boolean
-complex

### Data Types in NumPy
- i - integer
- u - unsigned integer
- f - float
- S - string
- b - boolean
- U - unicode
- O - object
- M - datetime
- m - timedelta
- V - fixed chunk of memory for other type (void)

In [10]:
# Checking the data type of an array

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int32


In [11]:
arr = np.array(['apple', 'banana', 'cherry', 'orange'])
print(arr.dtype)

<U6


In [12]:
arr = np.array([1, 2, 3, 4, 5], dtype='S')
print(arr.dtype)

before = id(arr)

|S1


In [13]:
arr= np.array([1, 2, 3, 4, 5], dtype='i4')
print(arr.dtype)
print(before == id(arr))

int32
False


In [14]:
# Automatically rounded to the nearest integer.
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [15]:
# ONly 0s are assigned as False and non-zero values are assigned as True.
arr = np.array([1, 0, 3, 2, 4])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True  True  True]
bool


### Numpy Array Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [16]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
x[0] = 10

print(arr)
print(x)

[1 2 3 4 5]
[10  2  3  4  5]


In [17]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [18]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


### Check if the array owns its data or not
Every NumPy array has the attribute base that returns None if the array owns the data.

In [19]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(arr.base)
print(x.base)
print(y.base)

None
None
[1 2 3 4 5]


In [20]:
# Numpy array shape
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr.shape)

(2, 5)


In [21]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr.shape)

(1, 1, 1, 1, 5)


In [22]:
# Munpy array reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.reshape(2, 3).base)

[1 2 3 4 5 6]


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr.reshape(2, -1)) # We can not pass -1 more than once in reshape function.

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [28]:
# flatting the array 

arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

newarr = arr.flatten()
print(newarr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [30]:
# Iterating Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

for x in arr:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [31]:
# Iterating Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [32]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [33]:
# Iterating Arrays with nditer

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [34]:
arr = np.array([1, 2, 3, 4, 5])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'


In [35]:
# Iterating the array with different step sizes

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
4
6
7
9


In [36]:
#Enumerated Iteration: indexs, and elements
arr = np.array([1, 2, 3, 4, 5])

for index, x in np.ndenumerate(arr):
    print(index, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [37]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
