In [43]:
import numpy as np
print(np.__version__)

1.26.4


In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(type(arr))

arr2 = np.array((1, 2, 3, 4, 5))
print(type(arr2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr4 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(arr3)
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [7]:
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

1
1
2
3


In [8]:
arr5 = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr5)

[[[[[1 2 3 4 5]]]]]


In [10]:
print('Last element of the array is:', arr3[1, -1])

Last element of the array is: 10


In [13]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr5[-3: -1])
print(arr5[2:8:2])

[8 9]
[3 5 7]


In [15]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


### Data Types in Python
- integer
- float
- string
- boolean
-complex

### Data Types in NumPy
- i - integer
- u - unsigned integer
- f - float
- S - string
- b - boolean
- U - unicode
- O - object
- M - datetime
- m - timedelta
- V - fixed chunk of memory for other type (void)

In [19]:
# Checking the data type of an array

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int32


In [21]:
arr = np.array(['apple', 'banana', 'cherry', 'orange'])
print(arr.dtype)

<U6


In [28]:
arr = np.array([1, 2, 3, 4, 5], dtype='S')
print(arr.dtype)

before = id(arr)

|S1


In [29]:
arr= np.array([1, 2, 3, 4, 5], dtype='i4')
print(arr.dtype)
print(before == id(arr))

|S1
True


In [30]:
# Automatically rounded to the nearest integer.
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [32]:
# ONly 0s are assigned as False and non-zero values are assigned as True.
arr = np.array([1, 0, 3, 2, 4])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True  True  True False]
bool


### Numpy Array Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [37]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
x[0] = 10

print(arr)
print(x)

[1 2 3 4 5]
[10  2  3  4  5]


In [38]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [39]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


### Check if the array owns its data or not
Every NumPy array has the attribute base that returns None if the array owns the data.

In [41]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(arr.base)
print(x.base)
print(y.base)

None
None
[1 2 3 4 5]


In [44]:
# Numpy array shape
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr.shape)

(2, 5)


In [46]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr.shape)

(1, 1, 1, 1, 5)


In [49]:
# Munpy array reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [50]:
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
