In [19]:
import torch

x = torch.rand(3, 5)
y = torch.arange(12)

X = x.view(-1, 3)
X_1 = x.reshape(5, 3)

print(x)
print(X)
print(X_1)
print(y)
print(y.shape)

tensor([[0.0681, 0.8331, 0.9526, 0.9872, 0.9794],
        [0.0584, 0.8417, 0.2033, 0.8751, 0.1639],
        [0.2736, 0.4847, 0.6092, 0.1503, 0.2873]])
tensor([[0.0681, 0.8331, 0.9526],
        [0.9872, 0.9794, 0.0584],
        [0.8417, 0.2033, 0.8751],
        [0.1639, 0.2736, 0.4847],
        [0.6092, 0.1503, 0.2873]])
tensor([[0.0681, 0.8331, 0.9526],
        [0.9872, 0.9794, 0.0584],
        [0.8417, 0.2033, 0.8751],
        [0.1639, 0.2736, 0.4847],
        [0.6092, 0.1503, 0.2873]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])


In [21]:
# Tensor operations
import torch
# 按位运算

x = torch.tensor([1, 1, 1])
y = torch.tensor([2, 2, 2])

print('Addition:', x + y)
print('Minus:', x - y)
print('Product:', x * y)
print('Division:', x / y)
print('Power:', x ** y)
print('exp:', torch.exp(y))

Addition: tensor([3, 3, 3])
Minus: tensor([-1, -1, -1])
Product: tensor([2, 2, 2])
Division: tensor([0.5000, 0.5000, 0.5000])
Power: tensor([1, 1, 1])
exp: tensor([7.3891, 7.3891, 7.3891])


In [23]:
# Tensor concatenate
import torch

X = torch.arange(12).view(3, 4)
Y = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

dim_0 = torch.cat((X, Y), dim=0)
dim_1 = torch.cat((X, Y), dim=1)

print('按行拼接：', dim_0)
print('按列拼接:', dim_1)

按行拼接： tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
按列拼接: tensor([[ 0,  1,  2,  3,  1,  2,  3,  4],
        [ 4,  5,  6,  7,  5,  6,  7,  8],
        [ 8,  9, 10, 11,  9, 10, 11, 12]])


In [26]:
# Tensor Logic Calculation
import torch

X = torch.arange(1, 13).view(3, 4)
Y = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [7, 10, 1, 12]])

print(X == Y)

tensor([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [False,  True, False,  True]])


In [27]:
# Tensor sum
import torch

Y = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [7, 10, 1, 12]])

print(Y.sum())

tensor(66)


In [28]:
# Tensor broadcasting
import torch

X = torch.tensor([[1, 2, 3]])
Y = torch.tensor([[1], [2], [3]])

print(X + Y)

# X 将复制行 ， Y 将复制列，然后按位相加

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])


In [8]:
# Tensor addition
import torch


x = torch.rand(3, 5)
y = torch.rand(3, 5)
# 1 torch.add()
result_1 = torch.empty(3, 5)

torch.add(x, y, out= result_1)

print('result_1 = ', result_1)

# 2 tensor.add_()  Notice: 可以改变tensor量的操作都带有_后缀， 例如 x.copy_(y), x.t_() 都可以改变 x 变量
x.add_(y)

print('result_2 = ', x)

# 3 +
print('result_3 = ', torch.add(x, y))
# print('result_3 = ', x + y)

result_1 =  tensor([[0.9842, 0.3536, 0.3774, 0.8087, 1.5306],
        [1.1415, 1.4733, 1.0242, 1.2429, 0.6229],
        [0.7976, 1.3250, 1.4766, 1.2839, 0.9988]])
result_2 =  tensor([[0.9842, 0.3536, 0.3774, 0.8087, 1.5306],
        [1.1415, 1.4733, 1.0242, 1.2429, 0.6229],
        [0.7976, 1.3250, 1.4766, 1.2839, 0.9988]])
result_3 =  tensor([[1.5923, 0.5096, 0.6007, 1.0518, 2.3550],
        [1.7036, 2.2561, 1.5641, 1.7518, 0.9386],
        [0.9938, 1.7689, 1.9592, 1.9581, 1.8557]])


In [6]:
# Tensor access
import torch

x = torch.rand(3, 5)

print(x)
print(x[:, 0])

tensor([[0.1961, 0.0085, 0.9856, 0.6217, 0.9176],
        [0.4967, 0.2955, 0.7550, 0.2040, 0.1417],
        [0.1027, 0.3962, 0.7457, 0.5840, 0.2468]])
tensor([0.1961, 0.4967, 0.1027])


In [9]:
# Tensor size modify
import torch


x = torch.randn(4, 4)
y = x.view(16)
# -1 表示除给定维度外的其余维度的乘积
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [30]:
# Tensor <--> Numpy.array, Tensor 和 Numpy 的数组可以相互转换，并且两者转换后共享在 CPU 下的内存空间，即改变其中一个的数值，另一个变量也会随之改变。
import torch


x = torch.rand(3,5)
print(type(x))

y = x.numpy()
print(type(y))

x.add_(1)
print('new x = ', x)
print('new y = ', y)

# 如果一个Tensor 只有一个元素 可转化为标量
X = torch.tensor([3.5])

print(X.item(), float(X), int(X))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
new x =  tensor([[1.8702, 1.4758, 1.0227, 1.4007, 1.8095],
        [1.2431, 1.1115, 1.8159, 1.1938, 1.5355],
        [1.4178, 1.9793, 1.5806, 1.4242, 1.8741]])
new y =  [[1.8701982 1.4757583 1.0227349 1.4007101 1.8095424]
 [1.2431192 1.1115049 1.8159304 1.1937559 1.5355082]
 [1.4177542 1.9792607 1.5806082 1.4242103 1.8741156]]
3.5 3.5 3
